### ISSUE TITLE
[FE] Top Bar

### ISSUE THREAD

**Issue by ChidimmaOfodum** [ChidimmaOfodum/deskeando#22]
AS A Deskeando User
I WANT to use my e-mail address as my username
SO THAT I can easily access the desk booking system.

Acceptance criteria (=Business roles or Scenarios - Gherkin)

- A component bar with all the functionality buttons as per design.

**Comment by ChidimmaOfodum** [comment]
Hi @Nikolov87, did you move this to done by mistake

**Comment by Nikolov87** [comment]
Yes is, mistake.

**Comment by kavitappatil** [comment]
LGTM
