### ISSUE TITLE
[BE] View all bookings endpoint (USER)

### ISSUE THREAD

**Issue by ChidimmaOfodum** [ChidimmaOfodum/deskeando#24]
AS A Deskeando User
I WANT to use my e-mail address, when logged in
SO THAT I can view all my bookings

Acceptance criteria (=Business roles or Scenarios - Gherkin)

- Endpoint should list all bookings for a particular user
- Documentation on postman
- Return the appropriate error message

**Comment by kavitappatil** [comment]
LGTM
